# This is a basic workflow to help you get started with Actions

name: CI and CD for inspirational-quote-vue front-end project

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build and publish"
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master

      # Use the latest node to run npm install and test on vuejs project
      - name: npm install and test
        uses: actions/setup-node@master
      - run: npm install
      - run: npm test

      # Build and publish the docker image in docker-hub
      - name: Build and publish docker image to docker-hub
        uses: HurricanKai/Publish-Docker-Github-Action@master
        with:
          name: krishnathapa/inspirational-quote-vue
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
